apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: cn89uhpmt-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/cn89uhpmt-java-quarkus-gitops